### ISSUE TITLE
modular components

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [natefaubion/example-functional-compiler#4]
Since you have a common intermediate compilation language of system f, it would be really nice if you had a way of stringing your stages together with something like pipes package so that it would be easy to use your modules with differing compilation targets.

Interoperability seems to be severely lacking in most compiler designs.

**Comment by natefaubion** [comment]
Thank you for the suggestion. The goal of this project is to be a straightforward teaching tool for a language frontend. It is not meant to be a tool to experiment with potentially more flexible architectures.
