### ISSUE TITLE
Arbitrary Point of Entry Compilation

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [natefaubion/example-functional-compiler#6]
[https://www.youtube.com/watch?v=wSdV1M7n4gQ](https://www.youtube.com/watch?v=wSdV1M7n4gQ) was very inspiring with how the language server starts compilation at the point of editing changes.

Is this something that you would consider?

**Comment by natefaubion** [comment]
Thank you for your interest. Per the project goals:
> This project is an example compiler frontend for a straightforward, statically-typed, functional language called Flub (functional Blub). It should illustrate an architecture for "real-world" language demands (ranges, error reporting, actual versus expected, etc.) while still being readable over a weekend.

I do not consider this in scope.
